### PR TITLE
Done with ConnectionView

### PR DESCRIPTION
**Pull request by nrkkalyan**
Hi,

I have done the connection view and also tested the same on Ubuntu.
Following are the changes :
1: Added support for Multiple connections
2: Upgraded to neo4j-1.6.M02
3: Added neo4j-rest libraries. But some issue while getting the relations from remote. I'm currently working on that.

Awaiting for your feedback.

### CODE REVIEW

**Comment by peterneubauer** [comment]
This looks very nice!

Some minor points:
- the URL in the example should probably be http://localhost:7474/db/data/ with the trailing /
- pointing the connection to localhost and starting it, I get IllegalArgumentException: Cannot get global operations at class org.neo4j.rest.graphdb.RestGraphDatabase
- I would like double-clicking on a connection stop the other active connection, if there is one, and automatically start it (and a right click menu for it - "Start this connection and close the others")

WDYT?

Great work otherwise, Merry XMas!

**Comment by nrkkalyan** [comment]
Hi,

Thanks for your comments. Currently rest is not supported as there is no
support to read the relations over rest.
That is my next task.

Regarding other modifications, I will add a checkbox on create new
connection dialog to take a input from the user if the connection to be
autostart or not.

Regarding double click starting and stopping is a good idea but only for
the connection which is selected.
I will work on that now.

Please let me know if you need any other changes.

Kalyan

On Sat, Dec 24, 2011 at 2:46 PM, Peter Neubauer <
reply@reply.github.com

> wrote:
> 
> This looks very nice!
> 
> Some minor points:
> - the URL in the example should probably be http://localhost:7474/db/data/with the training /
> - pointing the connection to localhost and starting it, I get
>   IllegalArgumentException: Cannot get global operations at class
>   org.neo4j.rest.graphdb.RestGraphDatabase
> - I would like double-clicking on a connection stop the other active
>   connection, if there is one, and automatically start it (and a right click
>   menu for it - "Start this connection and close the others")
> 
> WDYT?
> 
> Great work otherwise, Merry XMas!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/neo4j/neoclipse/pull/14#issuecomment-3267785

## 

Thanks and Regards
N Radhakrishna Kalyan

**Comment by peterneubauer** [comment]
Perfect,
I think that will make a very nice connection view!

Cheers

/peter

Sent from a device with crappy keyboard and autocorrect
On Dec 24, 2011 5:59 PM, "Radhakrishna Kalyan" <
reply@reply.github.com>
wrote:

**Comment by nrkkalyan** [comment]
Hi Peter,

Right now we can only have a single connection at any point of time. Will
there be any problem if we support multiple connections. As it will be
nicer to see various graphs at the same time without closing any and more
over the user can compare the graphs too.

Kalyan

On Sat, Dec 24, 2011 at 6:08 PM, Peter Neubauer <
reply@reply.github.com

> wrote:
> 
> Perfect,
> I think that will make a very nice connection view!
> 
> Cheers
> 
> /peter
> 
> Sent from a device with crappy keyboard and autocorrect
> On Dec 24, 2011 5:59 PM, "Radhakrishna Kalyan" <
> reply@reply.github.com>
> wrote:
> 
> > Hi,
> > 
> > Thanks for your comments. Currently rest is not supported as there is no
> > support to read the relations over rest.
> > That is my next task.
> > 
> > Regarding other modifications, I will add a checkbox on create new
> > connection dialog to take a input from the user if the connection to be
> > autostart or not.
> > 
> > Regarding double click starting and stopping is a good idea but only for
> > the connection which is selected.
> > I will work on that now.
> > 
> > Please let me know if you need any other changes.
> > 
> > Kalyan
> > 
> > On Sat, Dec 24, 2011 at 2:46 PM, Peter Neubauer <
> > reply@reply.github.com
> > 
> > > wrote:
> > > 
> > > This looks very nice!
> > > 
> > > Some minor points:
> > > - the URL in the example should probably be
> > >   http://localhost:7474/db/data/with the training /
> > > - pointing the connection to localhost and starting it, I get
> > >   IllegalArgumentException: Cannot get global operations at class
> > >   org.neo4j.rest.graphdb.RestGraphDatabase
> > > - I would like double-clicking on a connection stop the other active
> > >   connection, if there is one, and automatically start it (and a right
> > >   click
> > >   menu for it - "Start this connection and close the others")
> > > 
> > > WDYT?
> > > 
> > > Great work otherwise, Merry XMas!
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/neo4j/neoclipse/pull/14#issuecomment-3267785
> > 
> > ## 
> > 
> > Thanks and Regards
> > N Radhakrishna Kalyan
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/neo4j/neoclipse/pull/14#issuecomment-3268304
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/neo4j/neoclipse/pull/14#issuecomment-3268328

## 

Thanks and Regards
N Radhakrishna Kalyan

**Comment by peterneubauer** [comment]
True,
in ebemedded mode there can only be an exclusive connection to the
graph. However, supporting multiple views would make for a tabbed
neoclipse main view with several connections to different DBs open at
the same time.

On Sun, Dec 25, 2011 at 1:07 PM, Radhakrishna Kalyan
reply@reply.github.com
wrote:

**Comment by nrkkalyan** [comment]
so do you think we must implement

On Sun, Dec 25, 2011 at 2:04 PM, Peter Neubauer <
reply@reply.github.com

> wrote:
> 
> True,
> in ebemedded mode there can only be an exclusive connection to the
> graph. However, supporting multiple views would make for a tabbed
> neoclipse main view with several connections to different DBs open at
> the same time.
> 
> On Sun, Dec 25, 2011 at 1:07 PM, Radhakrishna Kalyan
> reply@reply.github.com
> wrote:
> 
> > Hi Peter,
> > 
> > Right now we can only have a single connection at any point of time. Will
> > there be any problem if we support multiple connections. As it will be
> > nicer to see various graphs at the same time without closing any and more
> > over the user can compare the graphs too.
> > 
> > Kalyan
> > 
> > On Sat, Dec 24, 2011 at 6:08 PM, Peter Neubauer <
> > reply@reply.github.com
> > 
> > > wrote:
> > > 
> > > Perfect,
> > > I think that will make a very nice connection view!
> > > 
> > > Cheers
> > > 
> > > /peter
> > > 
> > > Sent from a device with crappy keyboard and autocorrect
> > > On Dec 24, 2011 5:59 PM, "Radhakrishna Kalyan" <
> > > reply@reply.github.com>
> > > wrote:
> > > 
> > > > Hi,
> > > > 
> > > > Thanks for your comments. Currently rest is not supported as there is
> > > > no
> > > > support to read the relations over rest.
> > > > That is my next task.
> > > > 
> > > > Regarding other modifications, I will add a checkbox on create new
> > > > connection dialog to take a input from the user if the connection to
> > > > be
> > > > autostart or not.
> > > > 
> > > > Regarding double click starting and stopping is a good idea but only
> > > > for
> > > > the connection which is selected.
> > > > I will work on that now.
> > > > 
> > > > Please let me know if you need any other changes.
> > > > 
> > > > Kalyan
> > > > 
> > > > On Sat, Dec 24, 2011 at 2:46 PM, Peter Neubauer <
> > > > reply@reply.github.com
> > > > 
> > > > > wrote:
> > > > > 
> > > > > This looks very nice!
> > > > > 
> > > > > Some minor points:
> > > > > - the URL in the example should probably be
> > > > >   http://localhost:7474/db/data/with the training /
> > > > > - pointing the connection to localhost and starting it, I get
> > > > >   IllegalArgumentException: Cannot get global operations at class
> > > > >   org.neo4j.rest.graphdb.RestGraphDatabase
> > > > > - I would like double-clicking on a connection stop the other active
> > > > >   connection, if there is one, and automatically start it (and a right
> > > > >   click
> > > > >   menu for it - "Start this connection and close the others")
> > > > > 
> > > > > WDYT?
> > > > > 
> > > > > Great work otherwise, Merry XMas!
> > > > > 
> > > > > ---
> > > > > 
> > > > > Reply to this email directly or view it on GitHub:
> > > > > https://github.com/neo4j/neoclipse/pull/14#issuecomment-3267785
> > > > 
> > > > ## 
> > > > 
> > > > Thanks and Regards
> > > > N Radhakrishna Kalyan
> > > > 
> > > > ---
> > > > 
> > > > Reply to this email directly or view it on GitHub:
> > > > https://github.com/neo4j/neoclipse/pull/14#issuecomment-3268304
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/neo4j/neoclipse/pull/14#issuecomment-3268328
> > 
> > ## 
> > 
> > Thanks and Regards
> > N Radhakrishna Kalyan
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/neo4j/neoclipse/pull/14#issuecomment-3270603
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/neo4j/neoclipse/pull/14#issuecomment-3270726

## 

Thanks and Regards
N Radhakrishna Kalyan

**Comment by peterneubauer** [comment]
I think we can wait a bit with that. Right now, double clicking on a
connection would then close the existing one, and start the new one. I
think that is a good first step to make switching between DBs easy.

On Sun, Dec 25, 2011 at 2:13 PM, Radhakrishna Kalyan
reply@reply.github.com
wrote:

**Comment by nrkkalyan** [comment]
Sure. Will take steps once current one gets more stable.

On Sun, Dec 25, 2011 at 2:16 PM, Peter Neubauer <
reply@reply.github.com

> wrote:
> 
> I think we can wait a bit with that. Right now, double clicking on a
> connection would then close the existing one, and start the new one. I
> think that is a good first step to make switching between DBs easy.
> 
> On Sun, Dec 25, 2011 at 2:13 PM, Radhakrishna Kalyan
> reply@reply.github.com
> wrote:
> 
> > so do you think we must implement
> > 
> > On Sun, Dec 25, 2011 at 2:04 PM, Peter Neubauer <
> > reply@reply.github.com
> > 
> > > wrote:
> > > 
> > > True,
> > > in ebemedded mode there can only be an exclusive connection to the
> > > graph. However, supporting multiple views would make for a tabbed
> > > neoclipse main view with several connections to different DBs open at
> > > the same time.
> > > 
> > > On Sun, Dec 25, 2011 at 1:07 PM, Radhakrishna Kalyan
> > > reply@reply.github.com
> > > wrote:
> > > 
> > > > Hi Peter,
> > > > 
> > > > Right now we can only have a single connection at any point of time.
> > > > Will
> > > > there be any problem if we support multiple connections. As it will be
> > > > nicer to see various graphs at the same time without closing any and
> > > > more
> > > > over the user can compare the graphs too.
> > > > 
> > > > Kalyan
> > > > 
> > > > On Sat, Dec 24, 2011 at 6:08 PM, Peter Neubauer <
> > > > reply@reply.github.com
> > > > 
> > > > > wrote:
> > > > > 
> > > > > Perfect,
> > > > > I think that will make a very nice connection view!
> > > > > 
> > > > > Cheers
> > > > > 
> > > > > /peter
> > > > > 
> > > > > Sent from a device with crappy keyboard and autocorrect
> > > > > On Dec 24, 2011 5:59 PM, "Radhakrishna Kalyan" <
> > > > > reply@reply.github.com>
> > > > > wrote:
> > > > > 
> > > > > > Hi,
> > > > > > 
> > > > > > Thanks for your comments. Currently rest is not supported as there
> > > > > > is
> > > > > > no
> > > > > > support to read the relations over rest.
> > > > > > That is my next task.
> > > > > > 
> > > > > > Regarding other modifications, I will add a checkbox on create new
> > > > > > connection dialog to take a input from the user if the connection
> > > > > > to
> > > > > > be
> > > > > > autostart or not.
> > > > > > 
> > > > > > Regarding double click starting and stopping is a good idea but
> > > > > > only
> > > > > > for
> > > > > > the connection which is selected.
> > > > > > I will work on that now.
> > > > > > 
> > > > > > Please let me know if you need any other changes.
> > > > > > 
> > > > > > Kalyan
> > > > > > 
> > > > > > On Sat, Dec 24, 2011 at 2:46 PM, Peter Neubauer <
> > > > > > reply@reply.github.com
> > > > > > 
> > > > > > > wrote:
> > > > > > > 
> > > > > > > This looks very nice!
> > > > > > > 
> > > > > > > Some minor points:
> > > > > > > - the URL in the example should probably be
> > > > > > >   http://localhost:7474/db/data/with the training /
> > > > > > > - pointing the connection to localhost and starting it, I get
> > > > > > >   IllegalArgumentException: Cannot get global operations at class
> > > > > > >   org.neo4j.rest.graphdb.RestGraphDatabase
> > > > > > > - I would like double-clicking on a connection stop the other
> > > > > > >   active
> > > > > > >   connection, if there is one, and automatically start it (and a
> > > > > > >   right
> > > > > > >   click
> > > > > > >   menu for it - "Start this connection and close the others")
> > > > > > > 
> > > > > > > WDYT?
> > > > > > > 
> > > > > > > Great work otherwise, Merry XMas!
> > > > > > > 
> > > > > > > ---
> > > > > > > 
> > > > > > > Reply to this email directly or view it on GitHub:
> > > > > > > https://github.com/neo4j/neoclipse/pull/14#issuecomment-3267785
> > > > > > 
> > > > > > ## 
> > > > > > 
> > > > > > Thanks and Regards
> > > > > > N Radhakrishna Kalyan
> > > > > > 
> > > > > > ---
> > > > > > 
> > > > > > Reply to this email directly or view it on GitHub:
> > > > > > https://github.com/neo4j/neoclipse/pull/14#issuecomment-3268304
> > > > > 
> > > > > ---
> > > > > 
> > > > > Reply to this email directly or view it on GitHub:
> > > > > https://github.com/neo4j/neoclipse/pull/14#issuecomment-3268328
> > > > 
> > > > ## 
> > > > 
> > > > Thanks and Regards
> > > > N Radhakrishna Kalyan
> > > > 
> > > > ---
> > > > 
> > > > Reply to this email directly or view it on GitHub:
> > > > https://github.com/neo4j/neoclipse/pull/14#issuecomment-3270603
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/neo4j/neoclipse/pull/14#issuecomment-3270726
> > 
> > ## 
> > 
> > Thanks and Regards
> > N Radhakrishna Kalyan
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/neo4j/neoclipse/pull/14#issuecomment-3270738
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/neo4j/neoclipse/pull/14#issuecomment-3270745

## 

Thanks and Regards
N Radhakrishna Kalyan

**Comment by nrkkalyan** [comment]
Hi Peter,

I have done with the changes you asked for. Can you please let me know if this works fine. And we are good to go.
If this is fine then I will start working on the unit test cases and fixing Null pointers during search.

Kalyan

**Comment by peterneubauer** [comment]
Thanks @nrkkalyan , did some spelling changes, otherwise this is in now, coolio!

**Pull request merged**
