### PR TITLE
Switch to Neo4J 2.0.0

### PR DESCRIPTION
**Pull request by manandbytes**

### CODE REVIEW

**Comment by nawroth** [comment]
There's still some missing pieces, for example it still uses the 1.9.5 dependency bundle (but the first part of the build will install a 2.0.0 dependency bundle). Thus it sort of works, but will still use the 1.9.5 artifacts (if the 1.9.5 bundle is available). I tried fixing it, but got into trouble with OSGi not being able to resolve dependencies, I guess I did something wrong. Once that has been sorted out, API incompatibilities will surface. Not sure how many though.

Also note that for Neo4j 2.0.0 JavaSE-1.7 is required.

**Comment by nawroth** [comment]
Trying this out, I'm getting `org.neo4j.kernel.impl.storemigration.UpgradeNotAllowedByConfigurationException` when trying to upgrade a store, even after checking the "allow" checkbox in the connection dialog (and restarting).

Other than that, it seems to work fine with 2.0.0 dbs. It gets rather obvious that you can't create a node unless there already is one!

Sometimes disconnecting from an embedded db is super slow. I haven't digged into that, don't know if this is a new problem or not.

Removing the examples is fine with me, I'd suggest keeping that commit.

How about merging what we have here into master, and then go for fixing more issues before releasing it. WDYT @manandbytes ? Or fix some more issue here before merging the PR?

**Comment by manandbytes** [comment]
```
 Or fix some more issue here before merging the PR?
```

There are some unused dependencies, see #61 

```
How about merging what we have here into master, and then go for fixing more issues
before releasing it. WDYT @manandbytes ?
```

I'll update this PR in a couple hours and will:
- drop examples
- allow upgrading
- switch to JavaSE-1.7 Runtime Environment

**Comment by manandbytes** [comment]
@nawroth Done.

```
There are some unused dependencies, see #61 
```

#61 could be (rebased and) applied later

**Pull request merged**
